# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Submit a new Testing Build pointing to staging to Apple TestFlight"
  lane :testflight do
    certificates_appstore
    gym(scheme: "ElectricNorth")
    upload_to_testflight(
      skip_submission: true,
      notify_external_testers: false,
      skip_waiting_for_build_processing: true 
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    cocoapods
    certificates_appstore
    gym(scheme: "ElectricNorth")
    deliver(skip_screenshots: true, force: true)
  end
  desc "Sync appstore certificates via match (readonly)"
  lane :certificates_appstore do
    match(app_identifier: ["deda9.Bitrise-Example"], type: "appstore", readonly: true)
  end
end
